[workspace]
resolver = "3"
members = [
  "parser",
  "examples/get-statistic",
  "examples/parse-events",
  "examples/parse-references",
]

[profile.release]
lto = true
codegen-units = 1
# strip = true

[profile.bench]
debug = true
